version: "3.9"
services:
  development:
    image: py-node-dev
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null

  flask-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: api
    command: flask run --host=0.0.0.0 --port=5001
    env_file:
      - .env

  react-app:
    image: node:16
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    working_dir: /app
    command: npm start

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db-pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  db-pgdata:
